### ISSUE TITLE
java.io.FileNotFoundException after update

### ISSUE THREAD

**Issue by SaiCode-DHBW** [thecolonel63/server-side-replay-recorder#2]
```
[08:10:01] [Server thread/INFO]: [STDERR]: java.io.FileNotFoundException: /home/container/replay_recordings/Geeganttextures�ewogICJ0aW1lc3RhbXAiIDogMTY1NjI1Mzg5Njc1MSwKICAicHJvZmlsZUlkIiA6ICI1YTYyZGJmNzZjNDc0YThhOTY4ZTMyOWFhMWZiODgwNCIsCiAgInByb2ZpbGVOYW1lIiA6ICJHZWVnYW50byIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mY2VjZWRmODU1MDBlZjFiNzIxMzVkNDFmYjcxMzYyZmVkNzEwMDRhZDJlZmJhOWZkZjBhMzgyZjBkYjc4ZThkIgogICAgfQogIH0KfQ==�PfzBN1j0LA+IvlraMuDUkNoC0kOTv+R3nEDarDjY8sKfy1bdzGlUAXhNtkwqoSqUFxP0KtfGGayYOfnerthtzbxoGlVMdB7ZT53hjSNkME4jegkMLfUsHgzmKy9eyz2K1odsOIi9F1Gxzq66iSflWAsO/qOhS4RB6ONAx/Xho4SDkRNpkcUERvyUmPXDmDn/Fi0bf6GkTG8RVErelkRoQnhznvkqDvJQ15Wt/kEOhGi2XVN0GPnTRr7hqj8BvB273V0m5pBadZyxPGKjLyYiH45xKAutWIHBqiK2x8x3e6iXBrGE5tSXGHDq/HONgfqNBwFm7HbGyClAkZD/750qCBMPMGruOKUd4y1F/PDsnV5fAuCE+mgtW6/Qw/7YGrGeecoxoCBH2viNXNBLYujAvuqNEnerJvOlG56oqN6fceCwtKC8Lpxr8q0wQfLLSIvvc05hNr2c/HzSCoNrKGOqzX9yPPcgwe4pNU9H9+P2XBHVwQOaIA87VpuK8Ht7z13yQa2JZ5ND4zRXQTESbvylT8o2Jb17y5aoZe1pwXCm8ZEo2APz/zrxDnjLA/5Wd/Kwwl5o9P7vbSV/v4xcmmo/+NSuqTm9VR2HA3oJhVIrKK7c3b3dzuOkw6ypJ0LI9RoJsoksAPeE9kySSDnhMnvN6grGCYyE0rA2lZkshS7ZoK8=/2022_07_12_17_00_07.mcpr (File name too long)
[08:10:01] [Server thread/INFO]: [STDERR]:      at java.base/java.io.FileOutputStream.open0(Native Method)
[08:10:01] [Server thread/INFO]: [STDERR]:      at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
[08:10:01] [Server thread/INFO]: [STDERR]:      at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
[08:10:01] [Server thread/INFO]: [STDERR]:      at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:123)
[08:10:01] [Server thread/INFO]: [STDERR]:      at com.thecolonel63.serversidereplayrecorder.util.FileHandlingUtility.zip(FileHandlingUtility.java:13)
[08:10:01] [Server thread/INFO]: [STDERR]:      at com.thecolonel63.serversidereplayrecorder.util.StoppedReplayFixer.fixReplay(StoppedReplayFixer.java:54)
[08:10:01] [Server thread/INFO]: [STDERR]:      at com.thecolonel63.serversidereplayrecorder.server.ServerSideReplayRecorderServer.lambda$fixStoppedReplays$4(ServerSideReplayRecorderServer.java:164)
[08:10:01] [Server thread/INFO]: [STDERR]:      at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[08:10:01] [Server thread/INFO]: [STDERR]:      at com.thecolonel63.serversidereplayrecorder.server.ServerSideReplayRecorderServer.fixStoppedReplays(ServerSideReplayRecorderServer.java:162)
[08:10:01] [Server thread/INFO]: [STDERR]:      at com.thecolonel63.serversidereplayrecorder.server.ServerSideReplayRecorderServer.init(ServerSideReplayRecorderServer.java:175)
[08:10:01] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.handler$bom000$onInitServer(MinecraftServer.java:6759)
[08:10:01] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:637)
[08:10:01] [Server thread/INFO]: [STDERR]:      at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
```

After updateing i run in that issue... but i cant figure out why because there is no such file

**Comment by thecolonel63** [comment]
To preface this: I apologize deeply for the delay. I released a patch to fix incomplete replays right before a big trip, and then I never had the chance to finally go back and fix it properly since then.

In any case if you're still having the issue I would say remove any folders from inside replay_recordings and try again.

I will eventually likely patch this if it hasn't been patched in the latest branch merge created by Metroite
