### ISSUE TITLE
1.20 does not work

### ISSUE THREAD

**Issue by LinRanAstra** [thecolonel63/server-side-replay-recorder#27]
I can't run it properly on the 1.20 fabric server
`[09:53:44] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/E:/ACG2/server/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[09:53:44] [main/INFO]: Compatibility level set to JAVA_17
[09:53:44] [main/INFO]: Loaded configuration file for Lithium: 115 options available, 2 override(s) found
[09:53:44] [main/INFO]: Successfully started async appender with [ServerGuiConsole, SysOut, File]
[09:53:45] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[09:53:45] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [vmp]) disables it and children
[09:53:45] [main/WARN]: Error loading class: com/ishland/c2me/notickvd/common/NoTickChunkSendingInterceptor (java.lang.ClassNotFoundException: com/ishland/c2me/notickvd/common/NoTickChunkSendingInterceptor)
[09:53:49] [main/WARN]: Method overwrite conflict for getConnection in fabric-networking-api-v1.mixins.json:accessor.ServerPlayNetworkHandlerAccessor from mod fabric-networking-api-v1, previously written by carpet.mixins.ServerGamePacketListenerImpl_coreMixin. Skipping method.
[09:53:50] [TISCM Mapping/INFO]: Yarn mapping file yarn-1.20+build.1-v2.tiny loaded
[09:53:50] [main/WARN]: Ksyxis will speedup your world loading. :P
[09:53:50] [main/WARN]: BUT IT MAY CAUSE ISSUES (INCLUDING COMPAT). DON'T ASK OTHER MODS' AUTHORS FOR COMPAT!
[09:53:51] [main/INFO]: ServerSideReplayRecorderServer loaded
[09:53:51] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'serversidereplayrecorder'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
Caused by: java.lang.RuntimeException: java.util.ServiceConfigurationError: com.fasterxml.jackson.databind.Module: Provider com.fasterxml.jackson.datatype.jsr310.JavaTimeModule not found
	at com.thecolonel63.serversidereplayrecorder.ServerSideReplayRecorderServer.loadConfig(ServerSideReplayRecorderServer.java:59) ~[serversidereplayrecorder-1.1.5-mc1.20.jar:?]
	at com.thecolonel63.serversidereplayrecorder.ServerSideReplayRecorderServer.onInitialize(ServerSideReplayRecorderServer.java:129) ~[serversidereplayrecorder-1.1.5-mc1.20.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	... 7 more
Caused by: java.util.ServiceConfigurationError: com.fasterxml.jackson.databind.Module: Provider com.fasterxml.jackson.datatype.jsr310.JavaTimeModule not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:593) ~[?:?]
	at java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219) ~[?:?]
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228) ~[?:?]
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273) ~[?:?]
	at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309) ~[?:?]
	at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393) ~[?:?]
	at com.fasterxml.jackson.databind.ObjectMapper.findModules(ObjectMapper.java:1131) ~[serversidereplayrecorder-1.1.5-mc1.20.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper.findModules(ObjectMapper.java:1115) ~[serversidereplayrecorder-1.1.5-mc1.20.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper.findAndRegisterModules(ObjectMapper.java:1165) ~[serversidereplayrecorder-1.1.5-mc1.20.jar:?]
	at com.thecolonel63.serversidereplayrecorder.ServerSideReplayRecorderServer.loadConfig(ServerSideReplayRecorderServer.java:52) ~[serversidereplayrecorder-1.1.5-mc1.20.jar:?]
	at com.thecolonel63.serversidereplayrecorder.ServerSideReplayRecorderServer.onInitialize(ServerSideReplayRecorderServer.java:129) ~[serversidereplayrecorder-1.1.5-mc1.20.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	... 7 more
`
Is there a solution?

**Comment by Moyettes** [comment]
Its Very Many Players Mod its not compatible

**Comment by thecolonel63** [comment]
Hello!

Sorry, but since this issue only happens with Very Many Players, which appears to deliberately change a few things that Server Side Replay Recorder is reliant on, this is not something that I can fix on my own.

I would recommend you contact the author of Very Many Players and have them reach out to me so we can collaborate towards compatibility between the two, but until then I would recommend you to disable either Very Many Players or Server Side Replay Recorder to start your server.

**Comment by thecolonel63** [comment]
I'm reopening this one because I'm thinking something is wrong with Server Side Replay Recorder - I'm not closing this until I can at least figure out what's causing the incompatibility.

**Comment by Moyettes** [comment]
Your right I thought it was Very Many Players because when i added the mods he was using I got a error and it was solved after I got rid of VMP.
For VMP I did find this out for my error, VMP they override tickEntityMovement in the ThreadedAnvilChunkStorage class and i was getting a cannot inject into error for SSRR mixin

This is for VMP

```
    @Overwrite
    public void tickEntityMovement() {
        try {
            this.nearbyEntityTracking.tick();
        } catch (Throwable t) {
            t.printStackTrace();
        }
    }
```

 and in Server Side Replay Recorder we try to put a mixin in it
    
```
   @Inject(method = "tickEntityMovement", at = @At(value = "INVOKE", target = "Lnet/minecraft/server/world/ThreadedAnvilChunkStorage$EntityTracker;updateTrackedStatus(Ljava/util/List;)V", ordinal = 0), locals = LocalCapture.CAPTURE_FAILHARD)
    void handleEntityMovement(CallbackInfo ci, List list, List list2, ObjectIterator var3, ThreadedAnvilChunkStorage.EntityTracker entityTracker, ChunkSectionPos chunkSectionPos, ChunkSectionPos chunkSectionPos2){
        ((RegionRecorderEntityTracker)entityTracker).updateTrackedStatus(((RegionRecorderWorld)this.world).getRegionRecorders());
    }
```
    
    
For VMP it can be solved with setting use_optimized_entity_tracking=false. As for the exact error that @MingriLingran got I was not able to recreate it using

serversidereplayrecorder-1.1.5-mc1.20
FerriteCore 6.0.0
vmp-fabric-mc1.20.1-0.2.0+beta.7.96-all
Lithium 0.11.2
Ksyxis-1.1
lithium-fabric-mc1.20.1-0.11.2
fabric-api-0.84.0+1.20.1
Fabric loader 0.14.21 For 1.20 or 1.20.1

If you can share more or even your whole log file so we can see what else mods are loaded. From the logs, those are the mods I found and everything worked after the VMP config change 


EDIT: I just saw the other issue, it was ledger

**Comment by thecolonel63** [comment]
As of release version 1.1.6, this issue has been fixed.

**Comment by BlueFunny19** [comment]
uhhhhhh
Can you tell me how this thing was fixed?
I have a 1.19.4 server that needs both Mods, but the update that fixes it doesn't apply to 1.19.4, and I'd like to backport it manually

**Comment by thecolonel63** [comment]
> 

It was fixed in the latest 1.20 release, and I can't backport it without a better way of supporting multiple versions at once.

**Comment by BlueFunny19** [comment]
I mean I'd like to manually backport this fix to 1.19.4 myself, but I'm not sure which code is fixing this (

**Comment by thecolonel63** [comment]
> I mean I'd like to manually backport this fix to 1.19.4 myself, but I'm not sure which code is fixing this (

If I recall correctly I fixed it by removing "yaml.findAndRegisterModules()" everywhere it was called in the config saving and loading code

**Comment by BlueFunny19** [comment]
Okay, thanks a lot.

**Comment by BlueFunny19** [comment]
uhhhhhh, I was wondering if this fix conflicts with Very Many Players or with Ledger?

**Comment by thecolonel63** [comment]
> uhhhhhh, I was wondering if this fix conflicts with Very Many Players or with Ledger?

Iirc, both. If it didn't fix it then I'm sorry but I can't help right now.
